services:
  database:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    expose:
      - "27020"
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
  api:
    build:
      context: .
    volumes:
      - "./:/app"
    environment:
      AUTH_KEY_URL: "${AUTH_KEY_URL}"
      REPO_TOKEN: "${REPO_TOKEN}"
      WEBHOOK_TOKEN: "${WEBHOOK_TOKEN}"
