services:
  database:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    ports:
      - "27018:27017" # For external debugging
  api:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      target: dev
    volumes:
      - "./:/app"
    ports:
      - "4000:8080"
    environment:
      DATABASE_URL: "mongodb://root:password@database:27017"
      AUTH_KEY_URL: "${AUTH_KEY_URL}"
      REPO_TOKEN: "${REPO_TOKEN}"
      WEBHOOK_TOKEN: "${WEBHOOK_TOKEN}"
      PRIVATE_PORT: "8080"
      PUBLIC_PORT: "4000"
