services:
  test:
    depends_on:
      - database
      - api
    build:
      target: test
    environment:
      AUTH_KEY_URL: "${AUTH_KEY_URL}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_URL: "${DATABASE_URL}"
      REPO_TOKEN: "${REPO_TOKEN}"
      WEBHOOK_TOKEN: "${WEBHOOK_TOKEN}"
