services:
  database:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - "27017"
  api:
    depends_on:
      - database
    build:
      context: .
      target: base
    environment:
      PORT: 80
      DATABASE_URL: "mongodb://root:password@database:27017"
    ports:
      - "4000:80"
    volumes:
      - "./:/app"
    command: ["npm", "run", "_dev"]
