services:
  database:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - "27017"
    ports:
      - "27018:27017" # For external debugging
    command: mongod --quiet --logpath /dev/null
  api:
    depends_on:
      - database
    build:
      context: .
      target: base
    env_file: ".env"
    ports:
      - "4000:80"
    volumes:
      - "./:/app"
    command: ["npm", "run", "_dev"]
