services:
  database:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - "27017"
    command: mongod --quiet --logpath /dev/null
  test:
    depends_on:
      - database
    build:
      target: test
    environment:
      AUTH_KEY_URL: "${AUTH_KEY_URL}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_URL: "${DATABASE_URL}"
      REPO_TOKEN: "${REPO_TOKEN}"
      WEBHOOK_TOKEN: "${WEBHOOK_TOKEN}"
