services:
  database:
    extends:
      file: "common.yml"
      service: database
    ports:
      - "27018:27017" # For external debugging
  api:
    depends_on:
      database:
        condition: service_healthy
    extends:
      file: "common.yml"
      service: api
    build:
      target: dev
    ports:
      - "4000:8080"
    environment:
      DATABASE_URL: "mongodb://root:password@database:27017"
      DATABASE_NAME: "activityService"
