# fly.toml app configuration file generated for activity-service on 2023-10-10T13:50:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "activity-service"
primary_region = "den"
kill_signal = "SIGINT"
kill_timeout = "5s"

[deploy]
	strategy = "immediate"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"
  build-target = "production"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

[[services.ports]]
	port = 80
	handlers = ["http"]
	force_https = true

[[services.ports]]
	port = 443
	handlers = ["tls", "http"]

[services.concurrency]
	type = "connections"
	hard_limit = 25
	soft_limit = 20

[[services.tcp_checks]]
	interval = "15s"
	timeout = "2s"
	grace_period = "1s"
