services:
  integration_tests:
    depends_on:
      - database
    build:
      context: ../
      target: base
    env_file:
      - ../.env
    environment:
      DATABASE_URL: "mongodb://root:password@database:27017"
    volumes:
      - "../:/app"
    command: ["npm", "run", "_test:integration:watch"]
  unit_tests:
    build:
      context: ../
      target: base
    env_file:
      - ../.env
    volumes:
      - "../:/app"
    command: ["npm", "run", "_test:unit:watch"]
