services:
  tests:
    depends_on:
      - database
    build:
      context: ../
      target: base
    environment:
      DATABASE_URL: "mongodb://root:password@database:27017"
    logging:
      driver: none
    command: ["npm", "run", "_test"]
