services:
  api:
    build:
      context: .
      target: base
    depends_on:
      - database
    ports:
      - "3000:80"
    environment:
      PORT: 80
      DATABASE_URL: "mongodb://root:password@database:27017"
    volumes:
      - "./:/app"
    command: ["npm", "run", "dev"]
  database:
    image: mongo:5.0.10-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - "27017"
    volumes:
      - ./database:/data/db
