name: CI

on:
  push:
    tags:
      - v*
env:
  FORCE_COLOR: 1
permissions: write-all
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        env:
          AUTH_KEY_URL: ${{vars.AUTH_KEY_URL}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          REPO_TOKEN: ${{secrets.REPO_TOKEN}}
          WEBHOOK_TOKEN: ${{secrets.WEBHOOK_TOKEN}}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set environment variables on fly.io
        env:
          AUTH_KEY_URL: ${{vars.AUTH_KEY_URL}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          REPO_TOKEN: ${{secrets.REPO_TOKEN}}
          WEBHOOK_TOKEN: ${{secrets.WEBHOOK_TOKEN}}
          SENTRY_DSN: ${{secrets.SENTRY_DSN}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_URL}}
        run: "flyctl secrets set DATABASE_URL=${DATABASE_URL} REPO_TOKEN=${REPO_TOKEN} WEBHOOK_TOKEN=${WEBHOOK_TOKEN} AUTH_KEY_URL=${AUTH_KEY_URL} SENTRY_URL=${SENTRY_URL}"
      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          SENTRY_DSN: ${{secrets.SENTRY_DSN}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_URL}}
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Publish release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "v${{ github.ref }}"
