name: CI

on:
  push:
    tags:
      - v*
env:
  FORCE_COLOR: 1
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files from repo
        uses: actions/checkout@v2
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout files from repo
        uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
